apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-data
  namespace: profile
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
